### ISSUE TITLE
Code Improvement: Modularize backend code

### ISSUE THREAD

**Issue by codeEmpress1** [wikimedia/WikiContrib#117]
It would be nice to make to backend code into modules, each modules doing a specific function. This would be in line with the SOLID principle of programming and  it would improve readability of the code.

**Comment by codeEmpress1** [comment]
@srish I will like to handle this issue

**Comment by srish** [comment]
@codeEmpress1 Hi! Thanks for filing this issue. I would want to put this task on a low priority for now as the interns are going to be making continuous changes to the project between now and the application deadline, due to which backend overhaul might not be the right timing, I think. This task can be revisited later.

**Comment by srish** [comment]
Closing this task for now, as there isn't an immediate need, I see around this.
