### ISSUE TITLE
[ignore] Redundancy in backend/WikiContrib/.gitignore

### ISSUE THREAD

**Issue by muskangupta-iitr** [wikimedia/WikiContrib#137]
Current `backend/WikiContrib/.gitignore` file looks like this:
```
static_cdn/
query/migrations/__pycache__/
result/migrations/__pycache__/
WikiContrib/.env
query/__pycache__/
WikiContrib/__pycache__/
result/__pycache__/
uploads/
query/management/__pycache__/
```
which can be reduced.
For ignoring `__pycache__`, we don't need to mention every folder pycache path. We can directly include only `__pycache__` and it will solve the problem.

One more problem is that the virtual environment is not included in the `.gitignore` file.
Like:
```
env/
venv/

# As per the backend installation steps
WMWikiContrib/
```
I would recommend to standardize the `.gitignore` file for the Django project.
@srish I would like to solve this issue.

**Comment by NdibeRaymond** [comment]
Hello @muskangupta-iitr , the .env wasn't put into .gitignore because we have no idea what each contributor will be naming their virtual environment. That means risking having something like
 .a/
.b/
.
.
.
.
.z/
Each one coming from different contributors and of no use to other users of the project. Instead it is advised that you add your environment into .git/info/exclude file. That way it won't bloat the .gitignore file with unnecessary ignores

**Comment by muskangupta-iitr** [comment]
@NdibeRaymond You are correct but atleast we should add some standard names as a part of standard `.gitignore` file for django project. We can also update the documentation and suggest them to name virtual environment as per standards but if they don't want to then we suggest alternatives as you suggested above.

**Comment by srish** [comment]
@muskangupta-iitr This issue is trivial and what @NdibeRaymond says about `.env` makes sense to me. 
(I'm closing this for now, we can re-open when the need arises)
