### ISSUE TITLE
Make improvements to the "incorrect usernames" warning dialog

### ISSUE THREAD

**Issue by srish** [wikimedia/WikiContrib#197]
I think the warning dialog needs improvements in two areas: 

**Design**

Current design:
<img width="1032" alt="Screen Shot 2020-06-10 at 6 20 42 PM" src="https://user-images.githubusercontent.com/288353/84335565-fb948b80-ab49-11ea-8f46-99e8b3acbafd.png">

Desired design (with content changes):
<img width="504" alt="Screen Shot 2020-06-10 at 6 40 31 PM" src="https://user-images.githubusercontent.com/288353/84335547-f1728d00-ab49-11ea-9b22-250811495c19.png">

When a user clicks no, then the dialog should disappear and user should be able to provide the information again.

**Positioning**
Currently, the warning dialog appears on the query page, which makes little sense to me. I think that until the user passes the `rapidfuzz` stage, they should not be redirected to the query page only to realize later that they have to enter all the information again and then for that go back to the login page. So, the warning dialog should appear on the login page itself.

**Comment by NdibeRaymond** [comment]
@srish I would like to say something about positioning. It is actually by design that it is so. we needed to account for when a user provides more than 1 user details (like in csv and multiple forms). Putting the dialog on the query page will mean the warning can't be personalized per user detail like it is currently being done. Currently, if you submit multiple user details and three of the details are wrong, the application will alert you three different times (each alert when you use the prev or next button to navigate to each of the pages). Doing this on the query page will mean it can only be done once (will be hard to user to figure out which user details is incorrect. And if we try to include the incorrect details in the dialog, things can easily become ugly).

Also, since we are already making network requests to fetch the full names, wouldn't it make more sense to fetch query results at once?

**Comment by srish** [comment]
@NdibeRaymond Ahha, I see. I got it now. So my few cents on this:
* We should add the username details as well in the warning box to highlight that warning belongs to which user.
* If someone doesn't want to proceed, how can they go back to the form and update it. Maybe hitting on the "No" button should take them to the form? But, probably, we have fetched results correctly at this point for other users that passed the `rapidfuzz` test?
* In any case, I think we can revisit this task in the second phase of the internship. That is when we need to decide on the future of the "Bulk Add" feature as well.

**Comment by srish** [comment]
After playing around with the tool recently, I feel that the dialog should be on the homepage itself (from UX perspective). Also, see my comment in #204, and so once we disable the list view, it shouldn't be a problem showcasing it on the homepage.
