### ISSUE TITLE
Provide at least one entry - Phabricator or Gerrit Username before making a search

### ISSUE THREAD

**Issue by Jain-Aditya** [wikimedia/WikiContrib#50]
There is no point making a search when a user omits both "Phabricator username" and "Gerrit Username" fields. We should probably display a message  "At least one field is required" or anything similar to that.

**Comment by rammanoj** [comment]
Cool feature! @Jain-Aditya 

The inputs can be given in two formats:
1. directly in the site
2. in the form of csv file.

If the user provide the usernames through the tool directly, then an error can be displayed whenever the both the usernames are not provided.

But if he/she uploads the usernames in the form of  csv file, validating all of them might be a complex task (as the list in csv file can go to hundreds and thousands). So, my suggestion is if both the username's are not provided, that field can be omitted while displaying the contributions. An error can be displayed to the user instead. 

For example:
In a query of 5 username's, if 3rd one does not have both gerrit and phabricator username's, 4th one can be displayed along with the error message saying something like "third entry can not be displayed because both phabricator and gerrit username's are not provided"

Any suggestions ?
