### ISSUE TITLE
Integrate list view of contributions of users added via CSV file upload feature

### ISSUE THREAD

**Issue by srish** [wikimedia/WikiContrib#58]
Visualization of contributions for users added via the CSV file upload feature in its current shape and form works well. One of the possible use cases of this feature -a hackathon scholarship committee uses it to eliminate applicants with little or no contributions to Wikimedia projects from the scholarship list. This feature can also help decide between promising candidates. Right now, the committee has to do manual work in choosing applicants. If not for finalizing candidates (as that requires manual review), at least for the initial elimination round, this feature can be used. But, for it to be useful for the committee, list view integration in a format shown below will help assess applicants quickly:

#### Users contributions: October 2018-September 2019

Name | Phabricator contributions | Gerrit contributions | Total contributions
-- | -- | -- | --
Srishti Sethi | x | y | sum of x and y
Rammanoj Potla | a | b | sum of a and b
Suchakra Sharma | c | d | sum of c and d
.. | .. | .. | ..

**Comment by rammanoj** [comment]
@srish This is one of the main features of the project. But I need to get the corresponding APIs to get the data. Where can I know about the different APIs available ?

**Comment by srish** [comment]
@rammanoj It looks like getting access to other APIs such as Bitergia isn't easy. I think it would make sense for us to try to gain access when we have a record of the bulk feature being useful to our platform users. 

Do you have a sense of how much time it might take if we are trying to pull information of let say ~200 users with Gerrit/Phabricator APIs we are already using?

**Comment by rammanoj** [comment]
Thanks @srish I will provide you with the detailed analysis soon. I know that it takes much time. But I will experiment it once again and give you the detailed explanation. 

It is not only with bitergia. Are there any other tools like it that provide us the data ? Are there any IRC channels to discuss about the APIs and stuff ?

**Comment by srish** [comment]
@rammanoj Sounds good! I think Bitergia might be the best route (if at all) as per the research you did during GSoC and my follow-up conversations with Andre. I was thinking about this feature a bit more. I imagine the loading of data for the list view can work similarly to how it works right now with the bulk view in chunks. If not 200 users at once, we can try to fetch information, let say for ~20 users, and show it on the list. There could be a "load more" button, clicking which only fetches the information of more users. Will this approach help you think?

**Comment by NdibeRaymond** [comment]
hello, I am an outreachy applicant and I would love to take up this feature implementation. I would need more details as to which approach is best, fetch everything once or fetch in batches?

**Comment by srish** [comment]
@NdibeRaymond Thanks for your interest in working on this issue! This is a big feature, and it might take a lot of time to implement it. I can imagine a microtask around this could be to investigate how much time does it take to fetch 20 users at once and what are the overall API limits with Phabricator and Gerrit. From there, we can decide whether or not this list view feature is feasible. If you are interested in working on the microtask I've shared above, feel free to file an issue around it and assign it to yourself!

**Comment by srish** [comment]
@rammanoj @tuxology please add anything, I may have missed here!

**Comment by NdibeRaymond** [comment]
> @NdibeRaymond Thanks for your interest in working on this issue! This is a big feature, and it might take a lot of time to implement it. I can imagine a microtask around this could be to investigate how much time does it take to fetch 20 users at once and what are the overall API limits with Phabricator and Gerrit. From there, we can decide whether or not this list view feature is feasible. If you are interested in working on the microtask I've shared above, feel free to file an issue around it and assign it to yourself!

ok. i will be working on the micro task then

**Comment by tuxology** [comment]
@NdibeRaymond Hi :wave: Thanks for working on this. So the issue and its current sate/workaround can be summarized as follows:

- While developing the list view, we identified that there are limits on the frequency of API calls we can do to fetch used info from Gerrit and Phabricator APIs. This means, it would take a long time to populate the complete table. This would not be very peasant UX as well as would require a lot of API calls each time we access the list views. 

- A possible workaround for this was to use the existing Bitergia installation and somehow access their APIs. Bitergia, by its design periodically stores and caches the data via one of its various internal modules (Ref: https://blog.bitergia.com/2018/05/01/perceval-software-project-data-at-your-will/). This allows Bitergia based API access to be fast and convenient and could be performed using elasticsearch. However, it was not possible to get the API access for Bitergia int he given timeframe of the project due to various reasons (administrative or otherwise). Andre and @rammanoj would explain it more.

- Current workaround was to replace the list view with a pager view. Upon searching a filled _list_ from the main page of WikiContrib, instead of presenting results in a list, we present a single page for the first user in the list. This way, each page is one user's query. Each page can be kind of _flipped_ using arrows on the sides of the page which take us to the next user in the list for whichw e make another small set of queries. to go to a specific user from the initial list, you can use the search bar and view their page. This was, we could avoid the issue of **list view** without sacrificing on the user experience. 

However, it seems list view is also very important as users have demanded. So the current microtask could be as follows:

1. Identify the actual limits of API call frequency for Gerrit and Phabricator  for each user. (Time taken to fetch all information for a single user) This was we could predict loading times for the list itself.

2. Estimate how much time it would take to populate an acceptable list size (maybe 30 per page) without sacrificing the user experience (we can paginate the list view itself)  

3. Propose a new architecture which would be able to reduce the API access tiem possibly by caching the queries in a periodic manner (the way Bitergia does) or possibly use Bitergia itself. Estimate how much time/efforts would it take to implement that.

**Comment by NdibeRaymond** [comment]
Since we are already making use of asyncio to fetch user commits asynchronously, I don't see a reason why we can't fetch the data of several users asynchronously too. Though the asyncio part of the codebase is a bit complicated, I think I am getting the hang of it. Currently experimenting on a way to achieve this. If it works, i think it will reduce total request time to by more than 80% or something close.
Any reason you think this wouldn't work @srish and @rammanoj  ?

**Comment by NdibeRaymond** [comment]
**UPDATE**
I have been looking at the perceval tool and it looks like something that has all the potentials to solve all the major problems we are facing here. Is there a reason we can't use this?

**Comment by NdibeRaymond** [comment]
**UPDATE**
The fact that internet speed varies around the globe and that servers speed are on a different level entirely compared to private user's internet speed makes it a bit more difficult to answer question of the time taken to fetch a single users data, and the time it would take to get user data for 20 - 30 users, since it all depends partly on the internet speed of the system making the API call.

To solve this, I modified WikiContrib (in ways that are un-mergeable). I will be submitting a PR soon with regards to that.
Anyone can clone it, upload csv files and see how long it takes to fetch the whole data based on there internet speed, then come to there own conclusion.
I believe this is a better approach than given fixed numbers that are guaranteed to vary based on location.

**Comment by srish** [comment]
@NdibeRaymond Thank you for documenting the research you did to understand what will be the pros and cons of using two different approaches. It might help as and when we move forward on implementing the list view. 

(I'm resetting the priority of this task to low, as we will put our focus 
 on https://github.com/wikimedia/WikiContrib#planned-features for now)

**Comment by srish** [comment]
I am closing this issue for now especially as we have #204 now.
